### PR TITLE
docs: add conda version badge and link to readme

### PR DESCRIPTION
**Pull request by cameronraysmith**
- [x] [](https://anaconda.org/conda-forge/hydra-zen)

### CODE REVIEW

**Review by rsokl — APPROVED** [review]

**Comment by rsokl** [comment]
Thanks for this! Sorry I failed to respond to your initial work on the conda-forge package. I meant to, but was very tied up  at the time.

**Comment by cameronraysmith** [comment]
You're welcome and not a problem at all! Thank you again for hydra-zen.

**Comment by rsokl** [comment]
@cameronraysmith heads up that v0.14.0 released on pypi today

**Comment by cameronraysmith** [comment]
Thank you! I'll look for the autotick pr. I've been migrating to rattler-build so may attempt to work that in as well.

**Comment by cameronraysmith** [comment]
https://github.com/conda-forge/hydra-zen-feedstock/pull/7

**Pull request merged**
